#!/usr/bin/env python3
"""
OpenClaw MGS Codec Dashboard - Configuration Wizard
Interactive setup for backend and frontend configuration
"""

import os
import sys
from pathlib import Path
from cryptography.fernet import Fernet


class Colors:
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    CYAN = '\033[0;36m'
    NC = '\033[0m'


def print_header(text):
    print(f"\n{Colors.CYAN}{'=' * 60}{Colors.NC}")
    print(f"{Colors.CYAN}{text:^60}{Colors.NC}")
    print(f"{Colors.CYAN}{'=' * 60}{Colors.NC}\n")


def print_info(text):
    print(f"{Colors.BLUE}ℹ{Colors.NC}  {text}")


def print_success(text):
    print(f"{Colors.GREEN}✓{Colors.NC}  {text}")


def print_warning(text):
    print(f"{Colors.YELLOW}⚠{Colors.NC}  {text}")


def get_input(prompt, default=None, required=False):
    """Get user input with optional default value"""
    if default:
        prompt_text = f"{Colors.CYAN}?{Colors.NC} {prompt} [{default}]: "
    else:
        prompt_text = f"{Colors.CYAN}?{Colors.NC} {prompt}: "

    while True:
        value = input(prompt_text).strip()

        if not value and default:
            return default

        if not value and required:
            print_warning("This field is required!")
            continue

        return value


def get_yes_no(prompt, default=True):
    """Get yes/no input"""
    default_text = "Y/n" if default else "y/N"
    prompt_text = f"{Colors.CYAN}?{Colors.NC} {prompt} [{default_text}]: "

    while True:
        value = input(prompt_text).strip().lower()

        if not value:
            return default

        if value in ['y', 'yes']:
            return True
        elif value in ['n', 'no']:
            return False
        else:
            print_warning("Please answer 'y' or 'n'")


def setup_backend_env():
    """Setup backend .env file"""
    print_header("Backend Configuration")

    backend_dir = Path(__file__).parent.parent / "backend"
    env_file = backend_dir / ".env"

    # Check if .env already exists
    if env_file.exists():
        overwrite = get_yes_no(".env file already exists. Overwrite?", default=False)
        if not overwrite:
            print_info("Keeping existing .env file")
            return

    config = {}

    # MongoDB URL
    print_info("MongoDB Configuration")
    config['MONGO_URL'] = get_input(
        "MongoDB URL",
        default="mongodb://localhost:27017/openclaw_db"
    )

    # Backend Port
    config['BACKEND_PORT'] = get_input(
        "Backend Port",
        default="8001"
    )

    # Secret Key
    print_info("\nSecurity Configuration")
    print_info("Generating encryption key for API tokens...")
    config['SECRET_KEY'] = Fernet.generate_key().decode()
    print_success("Encryption key generated")

    # Optional: Brave Search API
    print_info("\nOptional: Web Search Configuration")
    add_brave = get_yes_no("Do you want to enable web search? (requires Brave API key)", default=False)
    if add_brave:
        brave_key = get_input("Brave Search API Key", required=False)
        if brave_key:
            config['BRAVE_API_KEY'] = brave_key

    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# OpenClaw MGS Codec Backend Configuration\n")
        f.write("# Generated by setup wizard\n\n")

        for key, value in config.items():
            f.write(f"{key}={value}\n")

    print_success(f"Backend configuration saved to {env_file}")


def setup_frontend_env():
    """Setup frontend .env file"""
    print_header("Frontend Configuration")

    frontend_dir = Path(__file__).parent.parent / "frontend"
    env_file = frontend_dir / ".env"

    # Check if .env already exists
    if env_file.exists():
        overwrite = get_yes_no(".env file already exists. Overwrite?", default=False)
        if not overwrite:
            print_info("Keeping existing .env file")
            return

    config = {}

    # Backend URL
    backend_url = get_input(
        "Backend API URL",
        default="http://localhost:8001"
    )
    config['REACT_APP_BACKEND_URL'] = backend_url

    # Write .env file
    with open(env_file, 'w') as f:
        f.write("# OpenClaw MGS Codec Frontend Configuration\n")
        f.write("# Generated by setup wizard\n\n")

        for key, value in config.items():
            f.write(f"{key}={value}\n")

    print_success(f"Frontend configuration saved to {env_file}")


def show_summary():
    """Show configuration summary"""
    print_header("Configuration Summary")

    backend_env = Path(__file__).parent.parent / "backend" / ".env"
    frontend_env = Path(__file__).parent.parent / "frontend" / ".env"

    print_info("Configuration files created:")
    if backend_env.exists():
        print(f"  {Colors.GREEN}✓{Colors.NC} {backend_env}")
    if frontend_env.exists():
        print(f"  {Colors.GREEN}✓{Colors.NC} {frontend_env}")

    print()
    print_info("Next steps:")
    print("  1. Start the application: ./start.sh")
    print("  2. Open http://localhost:3000 in your browser")
    print("  3. Configure your API token in the dashboard")


def main():
    """Main wizard flow"""
    print(f"{Colors.GREEN}")
    print("""
    ╔═══════════════════════════════════════╗
    ║   Configuration Wizard                ║
    ║   OpenClaw MGS Codec Dashboard        ║
    ╚═══════════════════════════════════════╝
    """)
    print(f"{Colors.NC}")

    try:
        setup_backend_env()
        setup_frontend_env()
        show_summary()

        print(f"\n{Colors.GREEN}Configuration complete!{Colors.NC}\n")
        return 0

    except KeyboardInterrupt:
        print(f"\n\n{Colors.YELLOW}Setup cancelled by user{Colors.NC}")
        return 1
    except Exception as e:
        print(f"\n{Colors.RED}Error: {e}{Colors.NC}")
        return 1


if __name__ == "__main__":
    sys.exit(main())
